name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 10

      - run: pnpm install --frozen-lockfile

      - name: Run vitest
        run: pnpm run test:coverage
      - name: Run lint
        run: pnpm run lint
      # - name: Run typecheck
      #   run: pnpm run typecheck
